### ISSUE TITLE
problem with UIMFLibrary reading drift times from an older version of UIMF

### ISSUE THREAD

**Issue by bspratt** [PNNL-Comp-Mass-Spec/UIMF-Library#3]
This was found in the context of Skyline's use of UIMF via the ProteoWizard library, which uses UIMFLibrary under the covers.

Where we started - Yehia Ibrahim noticed that the drift times displayed in Skyline for his BSA data file seemed awfully small.  I investigated.  

I found a data set at http://omics.pnl.gov/software/lc-ims-ms-feature-finder (http://omics.pnl.gov/sites/default/files/software/LC-IMS-MS_Feature_Finder_Example_Data_0.zip) which has both UIMF and a CSV representation so I could sanity check our use of UIMFLibrary.

In that data set, frame 1 scan 93 in the CSV file suggests a drift time of 15.673 msec, but ProteoWizard shows it as "15.506197540541".  But it reads frame 1 scan 94 drift time as "15.672930847428".  

Using the demonstration code at https://github.com/PNNL-Comp-Mass-Spec/UIMF-Library I can verify that the proper drift times for frame 1 scans 93 and 94 are indeed as ProteoWizard reads them.  So, it seems that whatever made that CSV file has an off-by-one error, and that Skyline+ProteoWizard is reading the UIMF from  http://omics.pnl.gov/software/lc-ims-ms-feature-finder properly.

So, if Skyline is not in error, why do the drift times from Yehia's BSA data seem so small?  It comes down to this line in UIMFLibrary:DataReader:GetDriftTime() 
            return driftTime \* (FRAME_PRESSURE_STANDARD / framePressure);
where 
           private const double FRAME_PRESSURE_STANDARD = 4.0;

The framePressure value in the lc-ims-feature-finder example data is about 3.9 as read from the "RearIonFunnelPressure" field, so "FRAME_PRESSURE_STANDARD / framePressure" is a small scaling correction.  

In the BSA data set, however, frame pressure comes in at about 378, read from the "PressureBack" field (which the UIMFLibrary source code notes is an obsolete form of pressure notation).  Now the scaling correction is rather drastic and yields a very small value.

So, given a modern UIMF file, Skyline+ProteoWizard will do fine.  But I think we have located a problem in the PNNL UIMF reader library's handling of older UIMF files, and possibly an off-by-one error in lc-ims-feature-finder.

Thanks,

Brian

**Comment by alchemistmatt** [comment]
The February 23 commit updated the GetDriftTime function to add a new parameter named `normalizeByPressure` to handle situations like the one you found.  It's not fool proof, as the calling user would need to know to set that to "false" when working with an old data file, but it is available as an option.  Unfortunately, the UIMF format was a bit fluid for a while, so some of the earlier IMS data files can have "gotchas" like the one you found.
